# Generated by Django 5.0.7 on 2024-07-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите телеграм chat_id",
                max_length=50,
                null=True,
                verbose_name="Телеграм chat_id",
            ),
        ),
    ]
