# Generated by Django 5.0.7 on 2024-07-25 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Место"
                    ),
                ),
                ("time", models.TimeField(verbose_name="Время")),
                (
                    "action",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Действие"
                    ),
                ),
                (
                    "pleasant_habit",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("ежедневно", "Ежедневно"),
                            ("раз в 2 дня", "Раз в 2 дня"),
                            ("раз в 3 дня", "Раз в 3 дня"),
                            ("раз в 4 дня", "Раз в 4 дня"),
                            ("раз в 5 дня", "Раз в 5 дня"),
                            ("раз в 6 дня", "Раз в 6 дня"),
                            ("раз в 7 дня", "Раз в 7 дня"),
                        ],
                        default="Ежедневно",
                        max_length=100,
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Время на выполнение"
                    ),
                ),
                (
                    "publicity",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Призгак публичности",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
