# Generated by Django 5.0.7 on 2024-07-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="pleasant_habit",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Признак приятной привычки",
            ),
        ),
    ]
