# Generated by Django 5.0.7 on 2024-07-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_pleasant_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("ежедневно", "Ежедневно"),
                    ("раз в 2 дня", "Раз в 2 дня"),
                    ("раз в 3 дня", "Раз в 3 дня"),
                    ("раз в 4 дня", "Раз в 4 дня"),
                    ("раз в 5 дня", "Раз в 5 дня"),
                    ("раз в 6 дня", "Раз в 6 дня"),
                    ("раз в 7 дня", "Раз в 7 дня"),
                ],
                default="ежедневно",
                max_length=100,
                verbose_name="периодичность",
            ),
        ),
    ]
