# Generated by Django 5.0.7 on 2024-07-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата изменения"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Периодичность в днях"
            ),
        ),
    ]
